export const GETTING_POSTS = "GETTING_POSTS";
export const GETTING_POSTS_SUCCESS = "GETTING_POSTS_SUCCESS";
export const GETTING_POSTS_FAILED = "GETTING_POSTS_FAILED";


export const GETTING_USERS = "GETTING_USERS";
export const GETTING_USERS_SUCCESS = "GETTING_USERS_SUCCESS";
export const GETTING_USERS_FAILED = "GETTING_USERS_FAILED";